### ISSUE TITLE
Native sample rate of 44100 Hz possible?

### ISSUE THREAD

**Issue by mincequi** [HSU-ANT/gstpeaq#25]
Hi there and thanks for making this nice tool,

I already investigated your implementation and was wondering, if it could support 44100 Hz natively. I also had a look at the PEAQ spec, where the also seem to use 48 kHz only. Do you see any limitations? Or could we use an arbitrary sample rate?

Thanks in advance.

**Comment by martinholters** [comment]
This project is meant as an implementation of BS.1387-1 which, as you've noticed, is limited to 48 kHz. While there are certainly reasonable approaches for adjusting the algorithm to another sampling rate, I'm pretty sure that would involve choices to be made. And I'm afraid none of them would be ideal in the following sense: For band-limited input stimuli with an analytical description so that they can be synthesized for different sampling rates (e.g. sum of sinusoids), the algorithm should compute the same ODG irrespective of sampling rate. I don't think this is feasible for sampling rates other than maybe multiples of 48 kHz.

I therefore believe the best way to apply PEAQ to signals of another sampling rate is to resample the signals, as then the user (potentially) has control of the resampling process.

Leaving this issue open nonetheless in case you're not convinced.

**Comment by mincequi** [comment]
This sounds reasonable. I was just interested, whether other sample rates would be possible from the standard.
Google's audio quality estimator (https://github.com/google/visqol) also only supports 48kHz and suggests resampling if other sample rates shall be supported.
